[server]
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 200
address = "0.0.0.0"
port = 8502

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#2563eb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"

[logger]
level = "info" 